### PR TITLE
Transfer files - fix parsing error in progress bar

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

Fix the following issue when running `jf rt transfer-files` on Artifactory 6:
```
[🚨Error] strconv.ParseInt: parsing "": invalid syntax
```

### CODE REVIEW

**Review by eyalbe4 — APPROVED** [review]

**Comment by vaskinyy** [comment]
thanks for fixing this 🥇 ! Hopefully, we should be able to transfer our files from our old on-prem instance to the cloud now

**Comment by eyalbe4** [comment]
Looking forward to your feedback @vaskinyy.

**Comment by vaskinyy** [comment]
This fixes our issue, we are able to transfer the files now. Thanks!

**Comment by eyalbe4** [comment]
Thank you @vaskinyy!
We'd happy to receive additional feedback for the process in case you have any.

**Pull request merged**
