### PR TITLE
Support Gradle args with spaces

### PR DESCRIPTION
**Pull request by keeganjm-bsc**
- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by keeganjm-bsc** [comment]
@yahavi @eyalbe4 @RobiNino please review this PR.

**Comment by keeganjm-bsc** [comment]
@yahavi @eyalbe4 @RobiNino please approve for Frogbot scan. All tests and analysis have passed. This PR is a dependency for another PR in the jfrog-cli project

**Comment by keeganjm-bsc** [comment]
@yahavi @eyalb4doc @RobiNino Please approve this for the Frogbot Scan job so this PR can move forward.

**Comment by keeganjm-bsc** [comment]
@yahavi @eyalbe4 @RobiNino please review and merge. This PR is a dependency for another PR IN Jfrog-cli project here https://github.com/jfrog/jfrog-cli/pull/2029. We have been trying to get these changes merged for over 2 weeks now. Please review and merge these so we can move forward with this.

**Review by yahavi — APPROVED** [review]

**Comment by keeganjm-bsc** [comment]
@yahavi can you elaborate more on this? It is similar to the changes that were required for mvn command.

**Comment by yahavi** [comment]
@keeganjm-bsc I elaborated in pull requests at the JFrog CLi repository: https://github.com/jfrog/jfrog-cli/pull/2029#issuecomment-1614676286

Please let me know what you think.

**Comment by eyalbe4** [comment]
@keeganjm-bsc,
I believe this PR can be closed, since https://github.com/jfrog/jfrog-cli-core/pull/1072 already addresses this issie.
Let me know if you think otherwise.

**Pull request closed without merging**
