### PR TITLE
Feature/fix dotnet test

### PR DESCRIPTION
**Pull request by gabo89**
- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
adding some changes in jfrog-cli-core to let dotnet test work properly with jfrog build-info

### CODE REVIEW

**Comment by gabo89** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gabo89** [comment]
recheck

**Comment by RobiNino** [comment]
Hi @gabo89 ,
Thank you very much for your contribution!
A similar fix was already introduced in https://github.com/jfrog/jfrog-cli-core/pull/712, and is included in version 2.36.0 of JFrog CLI.
We'd appreciate your feedback for it.
Thanks a lot again!

**Comment by gabo89** [comment]
closing as it already implemented in another PR , thanks!

**Pull request closed without merging**
