### PR TITLE
move depTree logic from 'xrayutils.go' file

### PR DESCRIPTION
**Pull request by asafambar**
- [X] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [X] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [X] This pull request is on the dev branch.
- [X] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
The contract of the 'xrayutils.go' should be moved to the github.com/jfrog/jfrog-cli-security module.

**Comment by asafambar** [comment]
@eyalbe4 moved most logic from xrayutils to security repo, the file still have one function which is in use in the core project

**Comment by eyalbe4** [comment]
@eranturgeman / @attiasas / @hadarshjfrog -
Are you good with the removal of this code, and its addition to the jfrog-cli-security module? If so, I suggest we remove it only once the code is merged (or is about to be merged) to jfrog-cli-security, to allow us to release jfrog-cli at any point of time. 
Awaiting your green light to merge this.

**Review by attiasas — COMMENTED** [review]
LGTM.
This removed content is transferred at: https://github.com/jfrog/jfrog-cli-security/pull/61

`CreateXrayServiceManager` is still used here, other content was removed.

**Comment by eyalbe4** [comment]
Can we go ahead and merge this PR @attiasas?
Would you like to merge the relevant code to jfrog-cli-security first?

**Pull request merged**
