### PR TITLE
Gradle args with spaces fail the command execution

### PR DESCRIPTION
**Pull request by keeganjm-bsc**
- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by keeganjm-bsc** [comment]
This PR is related to https://github.com/jfrog/jfrog-cli/pull/921 and https://github.com/jfrog/jfrog-cli/pull/2029 is needed to pass in multiple tags with space. For example:
-Dkarate.options="--tags=@smoke --tags=~@regression"

This command fails when being passed as the gradle command using jfrog cli like so
'jfrog rt gradle clean assemble myTest -Dkarate.options="--tags=@smoke --tags=~@regression"'

Currently the gradleCmd is not taking the complete value of -Dkarate.options and is interpreting the white space in the command as a break in the cmd line argument for -Dkarate.options and is then looking at --tags as a commandline argument. Here is an example of how it is appearing in the logs.

'jfrog rt gradle clean assemble myTest -Dkarate.options=--tags=@smoke --tags=~@regression'

Note the space after '@smoke'. This is what appears to be causing us issues. As the error coming into our logs is saying --tags is not a command line argument.

**Comment by keeganjm-bsc** [comment]
@eyalbe4 is there anything I can do to move this forward to get reviewed? This PR is blocking another PR from being able to get tested and reviewed. If there is anything I can do from my end please let me know. Thanks!

**Comment by keeganjm-bsc** [comment]
@eyalbe4 Any update on this?

**Comment by keeganjm-bsc** [comment]
@eyalbe4 Is there anything I can do to get this PR moved forward? Please let me know

**Comment by keeganjm-bsc** [comment]
@yahavi Is there anything we can do to get this PR moved forward?

**Review by eyalbe4 — APPROVED** [review]

**Comment by eyalbe4** [comment]
I believe this PR can be closed, since https://github.com/jfrog/jfrog-cli-core/pull/1072 already addresses this issue.
Let us know if you think otherwise, and thanks for creating this @keeganjm-bsc!

**Pull request closed without merging**
